### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by DeleMike** [chemicoPy/lens_it#1]
I am here in this quite interesting repo but sadly I cannot see tips on how to test your code. 

Can you please update your README file so that it will tell us the go abouts for testing this program, maybe some requirements and softwares that needs to be installed before we can successfully test this project.

**Comment by chemicoPy** [comment]
Thank you Michael for calling my attention to this..

Had to quickly push the project for a reason and totally forgot to compose a README.

That's unprofessional of me by the way! 
I'll get on composing a good one. Please check back for update

**Comment by chemicoPy** [comment]
@DeleMike, I have updated the README now. Thank you!

**Comment by DeleMike** [comment]
Seen it. You are welcome!
